#ifndef DEFINES_H
#define DEFINES_H

#define TAM_ALUNO 10
#define TAM_PROFESSOR 10
#define TAM_DISCIPLINA 10

typedef enum {
  CAD_ALUNO_SUCESSO = -1,
  MATRICULA_INVALIDA = -2,
  LISTA_CHEIA = -3,
  ATUALIZACAO_ALUNO_SUCESSO = -4,
  MATRICULA_INEXISTENTE = -5,
  EXCLUSAO_ALUNO_SUCESSO = -6,
  CAD_PROF_SUCESSO = -7,
  ATUALIZACAO_PROF_SUCESSO = -8,
  EXCLUSAO_PROF_SUCESSO = -9,
  CAD_DISC_SUCESSO = -10,
  ATUALIZACAO_DISC_SUCESSO = -11,
  EXCLUSAO_DISC_SUCESSO = -12,
  CODIGO_INVALIDO = -13,
  CODIGO_INEXISTENTE = -14,
  OPCAO_INVALIDA = -15,
  CPF_INVALIDO = -16,
  DATA_INVALIDA = -17,
  DATA_VALIDA = -18
} StatusCodigo;

#endif